Merged PR 6348: Enable setting of "concurrency" in php.ini file.
Changes made:
- FEAT: Enabled setting of "concurrency" in php.ini file. Default value is 10. If 0 or negative values are specified, default value will be used.
- TEST: Added test script and updated CI to run the new test.
- DOC: Updated readme.md to details the new "concurrency" option.
- DOC: Updated SWIG wrapper generation section with details on how to generate SWIG wrapper files for PHP 8.0.

diff --git a/ci/shared-build-and-test-stage.yml b/ci/shared-build-and-test-stage.yml
--- a/ci/shared-build-and-test-stage.yml
+++ b/ci/shared-build-and-test-stage.yml
@@ -165,6 +165,13 @@ stages:
         # Setting FiftyOneDegreesHashEngine extension and datafile paths in php.ini
       - script: |
           export PHPVERSIONEXACT=`php-config --version | grep -o '^[0-9]\.[0-9]'`
+          echo "Backing up /etc/php/$PHPVERSIONEXACT/cli/php.ini"
+          sudo cp /etc/php/$PHPVERSIONEXACT/cli/php.ini /etc/php/$PHPVERSIONEXACT/cli/php.ini.org
+          if [[ $? != 0 ]]; then
+              echo "FAIL: Failed to back up php.ini"
+              exit 1
+          fi
+
           echo extension=`pwd`/on-premise/modules/FiftyOneDegreesHashEngine.so | sudo tee -a /etc/php/$PHPVERSIONEXACT/cli/php.ini
           echo FiftyOneDegreesHashEngine.data_file=`pwd`/on-premise/device-detection-cxx/device-detection-data/Enterprise-HashV41.hash | sudo tee -a /etc/php/$PHPVERSIONEXACT/cli/php.ini
           echo FiftyOneDegreesHashEngine.allow_unmatched=false | sudo tee -a /etc/php/$PHPVERSIONEXACT/cli/php.ini
@@ -209,3 +216,21 @@ stages:
           cd ..
         displayName: 'Run Performance Tests'
         failOnStderr: true
+
+      - script: |
+          export PHPVERSIONEXACT=`php-config --version | grep -o '^[0-9]\.[0-9]'`
+          if test -f /etc/php/$PHPVERSIONEXACT/cli/php.ini.org; then
+              echo "Reserved changes made to php.ini"
+              sudo cp /etc/php/$PHPVERSIONEXACT/cli/php.ini.org /etc/php/$PHPVERSIONEXACT/cli/php.ini
+              if [[ $? != 0 ]]; then
+                  echo "FAIL: Failed to reverse changes made to php.ini"
+                  exit 1
+              fi
+              # Remove backup file
+              sudo rm /etc/php/$PHPVERSIONEXACT/cli/php.ini.org
+          fi
+        displayName: 'Reverse changes made to php.ini'
+
+      - script: |
+          ./configuration-tests/testConcurrencySetting.sh
+        displayName: 'Run Concurrency Setting tests'
